"""Type definitions for Limitless Exchange SDK."""

from .logger import ILogger, NoOpLogger, ConsoleLogger, LogLevel
from .user import UserProfile, UserData
from .markets import (
    OrderbookEntry,
    OrderBook,
    MarketPrice,
    MarketOutcome,
    Market,
    MarketsResponse,
    ActiveMarketsSortBy,
    ActiveMarketsParams,
    ActiveMarketsResponse,
)
from .market_pages import (
    NavigationNode,
    FilterGroupOption,
    FilterGroup,
    BreadcrumbItem,
    MarketPage,
    PropertyOption,
    PropertyKey,
    OffsetPagination,
    CursorPagination,
    MarketPageSortField,
    MarketPageSort,
    MarketPageMarketsParams,
    MarketPageMarketsOffsetResponse,
    MarketPageMarketsCursorResponse,
    MarketPageMarketsResponse,
)
from .orders import (
    Side,
    OrderType,
    SignatureType,
    UnsignedOrder,
    SignedOrder,
    CreateOrderDto,
    CancelOrderDto,
    DeleteOrderBatchDto,
    MarketSlugValidator,
    ReceiveWindowOptions,
    OrderSigningConfig,
    OrderArgs,
    MakerMatch,
    OrderResponse,
)
from .api_tokens import (
    ScopeTrading,
    ScopeAccountCreation,
    ScopeDelegatedSigning,
    ScopeWithdrawal,
    HMACCredentials,
    ApiTokenProfile,
    DeriveApiTokenInput,
    DeriveApiTokenResponse,
    ApiToken,
    PartnerCapabilities,
)
from .partner_accounts import (
    CreatePartnerAccountInput,
    CreatePartnerAccountEOAHeaders,
    PartnerAccountResponse,
    ListPartnerAccountsParams,
    PartnerAccountListItem,
    ListPartnerAccountsResponse,
    PartnerWithdrawalAddressInput,
    PartnerWithdrawalAddressResponse,
    PartnerAccountAllowanceTypeUsdcAllowance,
    PartnerAccountAllowanceTypeCtfApproval,
    PartnerAccountAllowanceRequiredForBuy,
    PartnerAccountAllowanceRequiredForSell,
    PartnerAccountAllowanceStatusConfirmed,
    PartnerAccountAllowanceStatusMissing,
    PartnerAccountAllowanceStatusSubmitted,
    PartnerAccountAllowanceStatusFailed,
    PartnerAccountAllowanceErrorPrivySponsorshipUnavailable,
    PartnerAccountAllowanceErrorPrivySubmissionFailed,
    PartnerAccountAllowanceErrorRpcReadFailed,
    PartnerAccountAllowanceErrorRequestBudgetExceeded,
    PartnerAccountAllowanceSummary,
    PartnerAccountAllowanceTarget,
    PartnerAccountAllowanceResponse,
)
from .delegated_orders import (
    DelegatedOrderSubmission,
    CreateDelegatedOrderRequest,
    CancelResponse,
)
from .server_wallets import (
    RedeemServerWalletInput,
    WithdrawServerWalletInput,
    ServerWalletTransactionEnvelope,
    RedeemServerWalletResponse,
    WithdrawServerWalletResponse,
)
from .portfolio import (
    Position,
    HistoryEntry,
    HistoryResponse,
    PortfolioResponse,
)

__all__ = [
    # Logger types
    "ILogger",
    "NoOpLogger",
    "ConsoleLogger",
    "LogLevel",
    # User types
    "UserProfile",
    "UserData",
    # Market types
    "OrderbookEntry",
    "OrderBook",
    "MarketPrice",
    "MarketOutcome",
    "Market",
    "MarketsResponse",
    "ActiveMarketsSortBy",
    "ActiveMarketsParams",
    "ActiveMarketsResponse",
    "NavigationNode",
    "FilterGroupOption",
    "FilterGroup",
    "BreadcrumbItem",
    "MarketPage",
    "PropertyOption",
    "PropertyKey",
    "OffsetPagination",
    "CursorPagination",
    "MarketPageSortField",
    "MarketPageSort",
    "MarketPageMarketsParams",
    "MarketPageMarketsOffsetResponse",
    "MarketPageMarketsCursorResponse",
    "MarketPageMarketsResponse",
    # Order types
    "Side",
    "OrderType",
    "SignatureType",
    "UnsignedOrder",
    "SignedOrder",
    "CreateOrderDto",
    "CancelOrderDto",
    "DeleteOrderBatchDto",
    "MarketSlugValidator",
    "ReceiveWindowOptions",
    "OrderSigningConfig",
    "OrderArgs",
    "MakerMatch",
    "OrderResponse",
    # API-token / partner types
    "ScopeTrading",
    "ScopeAccountCreation",
    "ScopeDelegatedSigning",
    "ScopeWithdrawal",
    "HMACCredentials",
    "ApiTokenProfile",
    "DeriveApiTokenInput",
    "DeriveApiTokenResponse",
    "ApiToken",
    "PartnerCapabilities",
    "CreatePartnerAccountInput",
    "CreatePartnerAccountEOAHeaders",
    "PartnerAccountResponse",
    "ListPartnerAccountsParams",
    "PartnerAccountListItem",
    "ListPartnerAccountsResponse",
    "PartnerWithdrawalAddressInput",
    "PartnerWithdrawalAddressResponse",
    "PartnerAccountAllowanceTypeUsdcAllowance",
    "PartnerAccountAllowanceTypeCtfApproval",
    "PartnerAccountAllowanceRequiredForBuy",
    "PartnerAccountAllowanceRequiredForSell",
    "PartnerAccountAllowanceStatusConfirmed",
    "PartnerAccountAllowanceStatusMissing",
    "PartnerAccountAllowanceStatusSubmitted",
    "PartnerAccountAllowanceStatusFailed",
    "PartnerAccountAllowanceErrorPrivySponsorshipUnavailable",
    "PartnerAccountAllowanceErrorPrivySubmissionFailed",
    "PartnerAccountAllowanceErrorRpcReadFailed",
    "PartnerAccountAllowanceErrorRequestBudgetExceeded",
    "PartnerAccountAllowanceSummary",
    "PartnerAccountAllowanceTarget",
    "PartnerAccountAllowanceResponse",
    "DelegatedOrderSubmission",
    "CreateDelegatedOrderRequest",
    "CancelResponse",
    "RedeemServerWalletInput",
    "WithdrawServerWalletInput",
    "ServerWalletTransactionEnvelope",
    "RedeemServerWalletResponse",
    "WithdrawServerWalletResponse",
    # Portfolio types
    "Position",
    "HistoryEntry",
    "HistoryResponse",
    "PortfolioResponse",
]
